import type { Metadata } from "next";
import localFont from "next/font/local";
import AppShell from "@/components/AppShell";
import "./globals.css";

const pretendard = localFont({
  src: [
    { path: "./fonts/Pretendard-Regular.otf", weight: "400" },
    { path: "./fonts/Pretendard-Bold.otf", weight: "700" },
  ],
  variable: "--font-pretendard",
});

const parkDahyeon = localFont({
  src: "./fonts/온글잎 박다현체.ttf",
  variable: "--font-point",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ko"
      className={`${pretendard.variable} ${parkDahyeon.variable} h-full antialiased`}
    >
      <AppShell>{children}</AppShell>
    </html>
  );
}
